### ISSUE TITLE
Track Further

### ISSUE THREAD

**Issue by tmblog** [theshka/EmailTrack#1]
hello sorry to open as issue, this is more of a question.
How can I check if the mail went to junk folder? Is this possible?

**Comment by theshka** [comment]
Hi @tmblog, thanks for your question! I do not think it's possible to detect which folder on the mail client is downloading our tracking pixel. If so, it is not within the scope of this class, and I wouldn't seek to add support for this. 

That said, however, you may find some mail clients will send extra headers to your `$_SERVER` vars that you could use to determine if the client marked your message as spam, as with [MS Exchange](https://technet.microsoft.com/en-us/library/dn205071%28v=exchg.150%29.aspx) anti-spam headers. 

Unfortunately, many anti-spam software will see mail with a tracking pixel as junk mail, partly due to it's prevalence among spammers to determine if an email address is still 'live'. Sorry I couldn't be of more help.

**Comment by tmblog** [comment]
Thanks for the great info!
